image:
  file: .gitpod.Dockerfile

tasks:
  - command: cd client && trunk serve
    init: cd client && trunk build # Prebuild app so running trunk-serve would be much faster

ports:
  - port: 8080
    onOpen: notify
  - port: 3000
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    