[package]
name = "playground-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
axum = { version = "0.5.3", features = ["json"] }
base64 = "0.13.0"
git-version = "0.3.5"
glob = "0.3.0"
once_cell = "1.10.0"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
