[package]
name = "playground-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
axum = { version = "0.5.6", features = ["json"] }
base64 = "0.13.0"
git-version = "0.3.5"
glob = "0.3.0"
once_cell = "1.11.0"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.18.2", features = ["full"] }
tower-http = { version = "0.3.3", features = ["cors"] }

[features]
